name: Build Zorbix Renderer V4

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.4'

      - name: Build Zorbix
        run: gradle build --no-daemon

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: Zorbix-Renderer-V4
          path: build/libs/*.jar
